# Simple Multi-threaded Program

multithread:
	gcc -g -O0 -pthread -o multithread64 example.c
	gcc -g -O0 -pthread -o multithread32 -m32 example.c

.PHONY: clean
clean:
	rm multithread32 multithread64
