from unicorn.riscv_const import *

from .lib import Arch

class Riscv32(Arch):
    ARCH_ID = 0x70
    
    TRACKED_REGISTERS = [
        (UC_RISCV_REG_X0, '<I'),
        (UC_RISCV_REG_X1, '<I'),
        (UC_RISCV_REG_X2, '<I'),
        (UC_RISCV_REG_X3, '<I'),
        (UC_RISCV_REG_X4, '<I'),
        (UC_RISCV_REG_X5, '<I'),
        (UC_RISCV_REG_X6, '<I'),
        (UC_RISCV_REG_X7, '<I'),
        (UC_RISCV_REG_X8, '<I'),
        (UC_RISCV_REG_X9, '<I'),
        (UC_RISCV_REG_X10, '<I'),
        (UC_RISCV_REG_X11, '<I'),
        (UC_RISCV_REG_X12, '<I'),
        (UC_RISCV_REG_X13, '<I'),
        (UC_RISCV_REG_X14, '<I'),
        (UC_RISCV_REG_X15, '<I'),
        (UC_RISCV_REG_X16, '<I'),
        (UC_RISCV_REG_X17, '<I'),
        (UC_RISCV_REG_X18, '<I'),
        (UC_RISCV_REG_X19, '<I'),
        (UC_RISCV_REG_X20, '<I'),
        (UC_RISCV_REG_X21, '<I'),
        (UC_RISCV_REG_X22, '<I'),
        (UC_RISCV_REG_X23, '<I'),
        (UC_RISCV_REG_X24, '<I'),
        (UC_RISCV_REG_X25, '<I'),
        (UC_RISCV_REG_X26, '<I'),
        (UC_RISCV_REG_X27, '<I'),
        (UC_RISCV_REG_X28, '<I'),
        (UC_RISCV_REG_X29, '<I'),
        (UC_RISCV_REG_X30, '<I'),
        (UC_RISCV_REG_X31, '<I'),
    ]
    
    REGISTER_NAMES = {
        UC_RISCV_REG_X0: 'X0', # 1
        #UC_RISCV_REG_ZERO: 'ZERO', # 1
        #UC_RISCV_REG_RA: 'RA', # 2
        UC_RISCV_REG_X1: 'X1', # 2
        #UC_RISCV_REG_SP: 'SP', # 3
        UC_RISCV_REG_X2: 'X2', # 3
        #UC_RISCV_REG_GP: 'GP', # 4
        UC_RISCV_REG_X3: 'X3', # 4
        #UC_RISCV_REG_TP: 'TP', # 5
        UC_RISCV_REG_X4: 'X4', # 5
        #UC_RISCV_REG_T0: 'T0', # 6
        UC_RISCV_REG_X5: 'X5', # 6
        #UC_RISCV_REG_T1: 'T1', # 7
        UC_RISCV_REG_X6: 'X6', # 7
        #UC_RISCV_REG_T2: 'T2', # 8
        UC_RISCV_REG_X7: 'X7', # 8
        #UC_RISCV_REG_FP: 'FP', # 9
        #UC_RISCV_REG_S0: 'S0', # 9
        UC_RISCV_REG_X8: 'X8', # 9
        #UC_RISCV_REG_S1: 'S1', # 10
        UC_RISCV_REG_X9: 'X9', # 10
        #UC_RISCV_REG_A0: 'A0', # 11
        UC_RISCV_REG_X10: 'X10', # 11
        #UC_RISCV_REG_A1: 'A1', # 12
        UC_RISCV_REG_X11: 'X11', # 12
        #UC_RISCV_REG_A2: 'A2', # 13
        UC_RISCV_REG_X12: 'X12', # 13
        #UC_RISCV_REG_A3: 'A3', # 14
        UC_RISCV_REG_X13: 'X13', # 14
        #UC_RISCV_REG_A4: 'A4', # 15
        UC_RISCV_REG_X14: 'X14', # 15
        #UC_RISCV_REG_A5: 'A5', # 16
        UC_RISCV_REG_X15: 'X15', # 16
        #UC_RISCV_REG_A6: 'A6', # 17
        UC_RISCV_REG_X16: 'X16', # 17
        #UC_RISCV_REG_A7: 'A7', # 18
        UC_RISCV_REG_X17: 'X17', # 18
        #UC_RISCV_REG_S2: 'S2', # 19
        UC_RISCV_REG_X18: 'X18', # 19
        #UC_RISCV_REG_S3: 'S3', # 20
        UC_RISCV_REG_X19: 'X19', # 20
        #UC_RISCV_REG_S4: 'S4', # 21
        UC_RISCV_REG_X20: 'X20', # 21
        #UC_RISCV_REG_S5: 'S5', # 22
        UC_RISCV_REG_X21: 'X21', # 22
        #UC_RISCV_REG_S6: 'S6', # 23
        UC_RISCV_REG_X22: 'X22', # 23
        #UC_RISCV_REG_S7: 'S7', # 24
        UC_RISCV_REG_X23: 'X23', # 24
        #UC_RISCV_REG_S8: 'S8', # 25
        UC_RISCV_REG_X24: 'X24', # 25
        #UC_RISCV_REG_S9: 'S9', # 26
        UC_RISCV_REG_X25: 'X25', # 26
        #UC_RISCV_REG_S10: 'S10', # 27
        UC_RISCV_REG_X26: 'X26', # 27
        #UC_RISCV_REG_S11: 'S11', # 28
        UC_RISCV_REG_X27: 'X27', # 28
        #UC_RISCV_REG_T3: 'T3', # 29
        UC_RISCV_REG_X28: 'X28', # 29
        #UC_RISCV_REG_T4: 'T4', # 30
        UC_RISCV_REG_X29: 'X29', # 30
        #UC_RISCV_REG_T5: 'T5', # 31
        UC_RISCV_REG_X30: 'X30', # 31
        #UC_RISCV_REG_T6: 'T6', # 32
        UC_RISCV_REG_X31: 'X31', # 32
        UC_RISCV_REG_USTATUS: 'USTATUS', # 33
        UC_RISCV_REG_UIE: 'UIE', # 34
        UC_RISCV_REG_UTVEC: 'UTVEC', # 35
        UC_RISCV_REG_USCRATCH: 'USCRATCH', # 36
        UC_RISCV_REG_UEPC: 'UEPC', # 37
        UC_RISCV_REG_UCAUSE: 'UCAUSE', # 38
        UC_RISCV_REG_UTVAL: 'UTVAL', # 39
        UC_RISCV_REG_UIP: 'UIP', # 40
        UC_RISCV_REG_FFLAGS: 'FFLAGS', # 41
        UC_RISCV_REG_FRM: 'FRM', # 42
        UC_RISCV_REG_FCSR: 'FCSR', # 43
        UC_RISCV_REG_CYCLE: 'CYCLE', # 44
        UC_RISCV_REG_TIME: 'TIME', # 45
        UC_RISCV_REG_INSTRET: 'INSTRET', # 46
        UC_RISCV_REG_HPMCOUNTER3: 'HPMCOUNTER3', # 47
        UC_RISCV_REG_HPMCOUNTER4: 'HPMCOUNTER4', # 48
        UC_RISCV_REG_HPMCOUNTER5: 'HPMCOUNTER5', # 49
        UC_RISCV_REG_HPMCOUNTER6: 'HPMCOUNTER6', # 50
        UC_RISCV_REG_HPMCOUNTER7: 'HPMCOUNTER7', # 51
        UC_RISCV_REG_HPMCOUNTER8: 'HPMCOUNTER8', # 52
        UC_RISCV_REG_HPMCOUNTER9: 'HPMCOUNTER9', # 53
        UC_RISCV_REG_HPMCOUNTER10: 'HPMCOUNTER10', # 54
        UC_RISCV_REG_HPMCOUNTER11: 'HPMCOUNTER11', # 55
        UC_RISCV_REG_HPMCOUNTER12: 'HPMCOUNTER12', # 56
        UC_RISCV_REG_HPMCOUNTER13: 'HPMCOUNTER13', # 57
        UC_RISCV_REG_HPMCOUNTER14: 'HPMCOUNTER14', # 58
        UC_RISCV_REG_HPMCOUNTER15: 'HPMCOUNTER15', # 59
        UC_RISCV_REG_HPMCOUNTER16: 'HPMCOUNTER16', # 60
        UC_RISCV_REG_HPMCOUNTER17: 'HPMCOUNTER17', # 61
        UC_RISCV_REG_HPMCOUNTER18: 'HPMCOUNTER18', # 62
        UC_RISCV_REG_HPMCOUNTER19: 'HPMCOUNTER19', # 63
        UC_RISCV_REG_HPMCOUNTER20: 'HPMCOUNTER20', # 64
        UC_RISCV_REG_HPMCOUNTER21: 'HPMCOUNTER21', # 65
        UC_RISCV_REG_HPMCOUNTER22: 'HPMCOUNTER22', # 66
        UC_RISCV_REG_HPMCOUNTER23: 'HPMCOUNTER23', # 67
        UC_RISCV_REG_HPMCOUNTER24: 'HPMCOUNTER24', # 68
        UC_RISCV_REG_HPMCOUNTER25: 'HPMCOUNTER25', # 69
        UC_RISCV_REG_HPMCOUNTER26: 'HPMCOUNTER26', # 70
        UC_RISCV_REG_HPMCOUNTER27: 'HPMCOUNTER27', # 71
        UC_RISCV_REG_HPMCOUNTER28: 'HPMCOUNTER28', # 72
        UC_RISCV_REG_HPMCOUNTER29: 'HPMCOUNTER29', # 73
        UC_RISCV_REG_HPMCOUNTER30: 'HPMCOUNTER30', # 74
        UC_RISCV_REG_HPMCOUNTER31: 'HPMCOUNTER31', # 75
        UC_RISCV_REG_CYCLEH: 'CYCLEH', # 76
        UC_RISCV_REG_TIMEH: 'TIMEH', # 77
        UC_RISCV_REG_INSTRETH: 'INSTRETH', # 78
        UC_RISCV_REG_HPMCOUNTER3H: 'HPMCOUNTER3H', # 79
        UC_RISCV_REG_HPMCOUNTER4H: 'HPMCOUNTER4H', # 80
        UC_RISCV_REG_HPMCOUNTER5H: 'HPMCOUNTER5H', # 81
        UC_RISCV_REG_HPMCOUNTER6H: 'HPMCOUNTER6H', # 82
        UC_RISCV_REG_HPMCOUNTER7H: 'HPMCOUNTER7H', # 83
        UC_RISCV_REG_HPMCOUNTER8H: 'HPMCOUNTER8H', # 84
        UC_RISCV_REG_HPMCOUNTER9H: 'HPMCOUNTER9H', # 85
        UC_RISCV_REG_HPMCOUNTER10H: 'HPMCOUNTER10H', # 86
        UC_RISCV_REG_HPMCOUNTER11H: 'HPMCOUNTER11H', # 87
        UC_RISCV_REG_HPMCOUNTER12H: 'HPMCOUNTER12H', # 88
        UC_RISCV_REG_HPMCOUNTER13H: 'HPMCOUNTER13H', # 89
        UC_RISCV_REG_HPMCOUNTER14H: 'HPMCOUNTER14H', # 90
        UC_RISCV_REG_HPMCOUNTER15H: 'HPMCOUNTER15H', # 91
        UC_RISCV_REG_HPMCOUNTER16H: 'HPMCOUNTER16H', # 92
        UC_RISCV_REG_HPMCOUNTER17H: 'HPMCOUNTER17H', # 93
        UC_RISCV_REG_HPMCOUNTER18H: 'HPMCOUNTER18H', # 94
        UC_RISCV_REG_HPMCOUNTER19H: 'HPMCOUNTER19H', # 95
        UC_RISCV_REG_HPMCOUNTER20H: 'HPMCOUNTER20H', # 96
        UC_RISCV_REG_HPMCOUNTER21H: 'HPMCOUNTER21H', # 97
        UC_RISCV_REG_HPMCOUNTER22H: 'HPMCOUNTER22H', # 98
        UC_RISCV_REG_HPMCOUNTER23H: 'HPMCOUNTER23H', # 99
        UC_RISCV_REG_HPMCOUNTER24H: 'HPMCOUNTER24H', # 100
        UC_RISCV_REG_HPMCOUNTER25H: 'HPMCOUNTER25H', # 101
        UC_RISCV_REG_HPMCOUNTER26H: 'HPMCOUNTER26H', # 102
        UC_RISCV_REG_HPMCOUNTER27H: 'HPMCOUNTER27H', # 103
        UC_RISCV_REG_HPMCOUNTER28H: 'HPMCOUNTER28H', # 104
        UC_RISCV_REG_HPMCOUNTER29H: 'HPMCOUNTER29H', # 105
        UC_RISCV_REG_HPMCOUNTER30H: 'HPMCOUNTER30H', # 106
        UC_RISCV_REG_HPMCOUNTER31H: 'HPMCOUNTER31H', # 107
        UC_RISCV_REG_MCYCLE: 'MCYCLE', # 108
        UC_RISCV_REG_MINSTRET: 'MINSTRET', # 109
        UC_RISCV_REG_MCYCLEH: 'MCYCLEH', # 110
        UC_RISCV_REG_MINSTRETH: 'MINSTRETH', # 111
        UC_RISCV_REG_MVENDORID: 'MVENDORID', # 112
        UC_RISCV_REG_MARCHID: 'MARCHID', # 113
        UC_RISCV_REG_MIMPID: 'MIMPID', # 114
        UC_RISCV_REG_MHARTID: 'MHARTID', # 115
        UC_RISCV_REG_MSTATUS: 'MSTATUS', # 116
        UC_RISCV_REG_MISA: 'MISA', # 117
        UC_RISCV_REG_MEDELEG: 'MEDELEG', # 118
        UC_RISCV_REG_MIDELEG: 'MIDELEG', # 119
        UC_RISCV_REG_MIE: 'MIE', # 120
        UC_RISCV_REG_MTVEC: 'MTVEC', # 121
        UC_RISCV_REG_MCOUNTEREN: 'MCOUNTEREN', # 122
        UC_RISCV_REG_MSTATUSH: 'MSTATUSH', # 123
        UC_RISCV_REG_MUCOUNTEREN: 'MUCOUNTEREN', # 124
        UC_RISCV_REG_MSCOUNTEREN: 'MSCOUNTEREN', # 125
        UC_RISCV_REG_MHCOUNTEREN: 'MHCOUNTEREN', # 126
        UC_RISCV_REG_MSCRATCH: 'MSCRATCH', # 127
        UC_RISCV_REG_MEPC: 'MEPC', # 128
        UC_RISCV_REG_MCAUSE: 'MCAUSE', # 129
        UC_RISCV_REG_MTVAL: 'MTVAL', # 130
        UC_RISCV_REG_MIP: 'MIP', # 131
        UC_RISCV_REG_MBADADDR: 'MBADADDR', # 132
        UC_RISCV_REG_SSTATUS: 'SSTATUS', # 133
        UC_RISCV_REG_SEDELEG: 'SEDELEG', # 134
        UC_RISCV_REG_SIDELEG: 'SIDELEG', # 135
        UC_RISCV_REG_SIE: 'SIE', # 136
        UC_RISCV_REG_STVEC: 'STVEC', # 137
        UC_RISCV_REG_SCOUNTEREN: 'SCOUNTEREN', # 138
        UC_RISCV_REG_SSCRATCH: 'SSCRATCH', # 139
        UC_RISCV_REG_SEPC: 'SEPC', # 140
        UC_RISCV_REG_SCAUSE: 'SCAUSE', # 141
        UC_RISCV_REG_STVAL: 'STVAL', # 142
        UC_RISCV_REG_SIP: 'SIP', # 143
        UC_RISCV_REG_SBADADDR: 'SBADADDR', # 144
        UC_RISCV_REG_SPTBR: 'SPTBR', # 145
        UC_RISCV_REG_SATP: 'SATP', # 146
        UC_RISCV_REG_HSTATUS: 'HSTATUS', # 147
        UC_RISCV_REG_HEDELEG: 'HEDELEG', # 148
        UC_RISCV_REG_HIDELEG: 'HIDELEG', # 149
        UC_RISCV_REG_HIE: 'HIE', # 150
        UC_RISCV_REG_HCOUNTEREN: 'HCOUNTEREN', # 151
        UC_RISCV_REG_HTVAL: 'HTVAL', # 152
        UC_RISCV_REG_HIP: 'HIP', # 153
        UC_RISCV_REG_HTINST: 'HTINST', # 154
        UC_RISCV_REG_HGATP: 'HGATP', # 155
        UC_RISCV_REG_HTIMEDELTA: 'HTIMEDELTA', # 156
        UC_RISCV_REG_HTIMEDELTAH: 'HTIMEDELTAH', # 157
        UC_RISCV_REG_F0: 'F0', # 158
        #UC_RISCV_REG_FT0: 'FT0', # 158
        UC_RISCV_REG_F1: 'F1', # 159
        #UC_RISCV_REG_FT1: 'FT1', # 159
        UC_RISCV_REG_F2: 'F2', # 160
        #UC_RISCV_REG_FT2: 'FT2', # 160
        UC_RISCV_REG_F3: 'F3', # 161
        #UC_RISCV_REG_FT3: 'FT3', # 161
        UC_RISCV_REG_F4: 'F4', # 162
        #UC_RISCV_REG_FT4: 'FT4', # 162
        UC_RISCV_REG_F5: 'F5', # 163
        #UC_RISCV_REG_FT5: 'FT5', # 163
        UC_RISCV_REG_F6: 'F6', # 164
        #UC_RISCV_REG_FT6: 'FT6', # 164
        UC_RISCV_REG_F7: 'F7', # 165
        #UC_RISCV_REG_FT7: 'FT7', # 165
        UC_RISCV_REG_F8: 'F8', # 166
        #UC_RISCV_REG_FS0: 'FS0', # 166
        UC_RISCV_REG_F9: 'F9', # 167
        #UC_RISCV_REG_FS1: 'FS1', # 167
        UC_RISCV_REG_F10: 'F10', # 168
        #UC_RISCV_REG_FA0: 'FA0', # 168
        UC_RISCV_REG_F11: 'F11', # 169
        #UC_RISCV_REG_FA1: 'FA1', # 169
        UC_RISCV_REG_F12: 'F12', # 170
        #UC_RISCV_REG_FA2: 'FA2', # 170
        UC_RISCV_REG_F13: 'F13', # 171
        #UC_RISCV_REG_FA3: 'FA3', # 171
        UC_RISCV_REG_F14: 'F14', # 172
        #UC_RISCV_REG_FA4: 'FA4', # 172
        UC_RISCV_REG_F15: 'F15', # 173
        #UC_RISCV_REG_FA5: 'FA5', # 173
        UC_RISCV_REG_F16: 'F16', # 174
        #UC_RISCV_REG_FA6: 'FA6', # 174
        UC_RISCV_REG_F17: 'F17', # 175
        #UC_RISCV_REG_FA7: 'FA7', # 175
        UC_RISCV_REG_F18: 'F18', # 176
        #UC_RISCV_REG_FS2: 'FS2', # 176
        UC_RISCV_REG_F19: 'F19', # 177
        #UC_RISCV_REG_FS3: 'FS3', # 177
        UC_RISCV_REG_F20: 'F20', # 178
        #UC_RISCV_REG_FS4: 'FS4', # 178
        UC_RISCV_REG_F21: 'F21', # 179
        #UC_RISCV_REG_FS5: 'FS5', # 179
        UC_RISCV_REG_F22: 'F22', # 180
        #UC_RISCV_REG_FS6: 'FS6', # 180
        UC_RISCV_REG_F23: 'F23', # 181
        #UC_RISCV_REG_FS7: 'FS7', # 181
        UC_RISCV_REG_F24: 'F24', # 182
        #UC_RISCV_REG_FS8: 'FS8', # 182
        UC_RISCV_REG_F25: 'F25', # 183
        #UC_RISCV_REG_FS9: 'FS9', # 183
        UC_RISCV_REG_F26: 'F26', # 184
        #UC_RISCV_REG_FS10: 'FS10', # 184
        UC_RISCV_REG_F27: 'F27', # 185
        #UC_RISCV_REG_FS11: 'FS11', # 185
        UC_RISCV_REG_F28: 'F28', # 186
        #UC_RISCV_REG_FT8: 'FT8', # 186
        UC_RISCV_REG_F29: 'F29', # 187
        #UC_RISCV_REG_FT9: 'FT9', # 187
        UC_RISCV_REG_F30: 'F30', # 188
        #UC_RISCV_REG_FT10: 'FT10', # 188
        UC_RISCV_REG_F31: 'F31', # 189
        #UC_RISCV_REG_FT11: 'FT11', # 189
        UC_RISCV_REG_PC: 'PC', # 190
    }

    VARFMT = "<I"
