FROM traceanalysis/dist

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -yq && apt-get install -y build-essential gcc jq

# Build the target
COPY target /app/target
WORKDIR /app/target
RUN make

# Add Scripts
COPY ./make_sysroot.sh /app/scripts/make_sysroot.sh

# Set starting directory
WORKDIR /app/out

# Run example when container starts up
COPY entrypoint-pin.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
